<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\AdminController;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/login');
Route::get('/login', [AuthController::class, 'showLogin'])->name('login');
Route::post('/login', [AuthController::class, 'login'])->name('login.attempt');
Route::get('/dashboard', [AuthController::class, 'dashboard'])->middleware('auth')->name('dashboard');
Route::put('/admin/account/password', [AuthController::class, 'updatePassword'])->middleware('auth')->name('admin.account.password');
Route::get('/admin/beneficiaries', [AdminController::class, 'beneficiaries'])->middleware('auth')->name('admin.beneficiaries');
Route::post('/admin/beneficiaries', [AdminController::class, 'storeBeneficiary'])->middleware('auth')->name('admin.beneficiaries.store');
Route::put('/admin/beneficiaries/{id}', [AdminController::class, 'updateBeneficiary'])->middleware('auth')->name('admin.beneficiaries.update');
Route::delete('/admin/beneficiaries/{id}', [AdminController::class, 'deleteBeneficiary'])->middleware('auth')->name('admin.beneficiaries.delete');
Route::post('/admin/beneficiaries/bulk-delete', [AdminController::class, 'bulkDeleteBeneficiaries'])->middleware('auth')->name('admin.beneficiaries.bulk-delete');
Route::post('/admin/beneficiaries/bulk-status', [AdminController::class, 'bulkStatusChange'])->middleware('auth')->name('admin.beneficiaries.bulk-status');
Route::get('/admin/beneficiaries/export', [AdminController::class, 'exportBeneficiaries'])->middleware('auth')->name('admin.beneficiaries.export');
Route::get('/admin/search', [AdminController::class, 'search'])->middleware('auth')->name('admin.search');
Route::get('/admin/inventory', [AdminController::class, 'inventory'])->middleware('auth')->name('admin.inventory');
Route::post('/admin/inventory', [AdminController::class, 'storeInventory'])->middleware('auth')->name('admin.inventory.store');
Route::put('/admin/inventory/{id}', [AdminController::class, 'updateInventory'])->middleware('auth')->name('admin.inventory.update');
Route::delete('/admin/inventory/{id}', [AdminController::class, 'deleteInventory'])->middleware('auth')->name('admin.inventory.delete');
Route::get('/admin/packages', [AdminController::class, 'packages'])->middleware('auth')->name('admin.packages');
Route::post('/admin/packages', [AdminController::class, 'storePackage'])->middleware('auth')->name('admin.packages.store');
Route::put('/admin/packages/{id}', [AdminController::class, 'updatePackage'])->middleware('auth')->name('admin.packages.update');
Route::delete('/admin/packages/{id}', [AdminController::class, 'deletePackage'])->middleware('auth')->name('admin.packages.delete');
Route::get('/admin/qr-codes', [AdminController::class, 'qrCodes'])->middleware('auth')->name('admin.qr-codes');
Route::post('/admin/qr-codes/generate/{id}', [AdminController::class, 'generateQRCode'])->middleware('auth')->name('admin.qr-codes.generate');
Route::get('/admin/qr-codes/download/{id}', [AdminController::class, 'downloadQRCode'])->middleware('auth')->name('admin.qr-codes.download');
Route::get('/admin/lost-qr', [AdminController::class, 'lostQr'])->middleware('auth')->name('admin.lost-qr');
Route::post('/admin/lost-qr/report/{id}', [AdminController::class, 'reportLostQr'])->middleware('auth')->name('admin.lost-qr.report');
Route::get('/admin/distribution', [AdminController::class, 'distribution'])->middleware('auth')->name('admin.distribution');
Route::post('/admin/distribution', [AdminController::class, 'storeDistribution'])->middleware('auth')->name('admin.distribution.store');
Route::put('/admin/distribution/{id}', [AdminController::class, 'updateDistribution'])->middleware('auth')->name('admin.distribution.update');
Route::delete('/admin/distribution/{id}', [AdminController::class, 'deleteDistribution'])->middleware('auth')->name('admin.distribution.delete');
Route::get('/admin/reports/inventory/export', [AdminController::class, 'exportInventoryReport'])->middleware('auth')->name('admin.reports.inventory-export');
Route::get('/admin/reports/export', [AdminController::class, 'exportReport'])->middleware('auth')->name('admin.reports.export');
Route::get('/admin/reports', [AdminController::class, 'reports'])->middleware('auth')->name('admin.reports');
Route::get('/admin/audit-logs', [AdminController::class, 'auditLogs'])->middleware('auth')->name('admin.audit-logs');
Route::match(['get', 'post'], '/admin/settings', [AdminController::class, 'settings'])->middleware('auth')->name('admin.settings');
Route::post('/logout', [AuthController::class, 'logout'])->middleware('auth')->name('logout');
